### ISSUE TITLE
Organize headers by directory?

### ISSUE THREAD

**Issue by mackthehobbit** [MCPE-Addons/MCPE-Headers#3]
It may be desirable to start organizing more of the headers by directories.

I would suggest that the best format is the directories used by the headers that were retrieved from the released DSYM back in 0.10.5, and new files will be placed logically.

**Comment by jose-vm** [comment]
We prefer using it without directory because sometimes it is confusing to find the folder where a header is, so that's why they're all stacked up in the same directory (with the exception of the packet and JSON headers)

**Comment by jose-vm** [comment]
Done.
